(cl:in-package N_Robot-srv)
(cl:export '(S32ERRCODE-VAL
          S32ERRCODE
          STRERRINFO-VAL
          STRERRINFO
          U8BATTOPEN-VAL
          U8BATTOPEN
          U8SWITCHDOWN-VAL
          U8SWITCHDOWN
          U8CHARGERIN-VAL
          U8CHARGERIN
          U8CHARGECOMP-VAL
          U8CHARGECOMP
          U8CHARGEOVERFLOW-VAL
          U8CHARGEOVERFLOW
          U8CHARGEROVERVOLT-VAL
          U8CHARGEROVERVOLT
          U8CHARGERVOLTLOW-VAL
          U8CHARGERVOLTLOW
          U8CHARGEROVERFLOW-VAL
          U8CHARGEROVERFLOW
))