(cl:in-package N_Robot-srv)
(cl:export '(S16DIRECTIONANGLE-VAL
          S16DIRECTIONANGLE
          U16CYCLER-VAL
          U16CYCLER
          U16LINEARVELOCITY-VAL
          U16LINEARVELOCITY
          S16ANGULARVELOCITY-VAL
          S16ANGULARVELOCITY
          S32ERRCODE-VAL
          S32ERRCODE
          STRERRINFO-VAL
          STRERRINFO
          U8SYSERRSTATUS-VAL
          U8SYSERRSTATUS
))