
(cl:in-package :asdf)

(defsystem "CDHF_Robot-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "NMotionCtrl_ResetAllMotorDriver_srv" :depends-on ("_package_NMotionCtrl_ResetAllMotorDriver_srv"))
    (:file "_package_NMotionCtrl_ResetAllMotorDriver_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_StartMotion_srv" :depends-on ("_package_NMotionCtrl_StartMotion_srv"))
    (:file "_package_NMotionCtrl_StartMotion_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_DefineMotorSpeed_srv" :depends-on ("_package_NMotionCtrl_DefineMotorSpeed_srv"))
    (:file "_package_NMotionCtrl_DefineMotorSpeed_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_ReadMotionStatus_srv" :depends-on ("_package_NMotionCtrl_ReadMotionStatus_srv"))
    (:file "_package_NMotionCtrl_ReadMotionStatus_srv" :depends-on ("_package"))
    (:file "CmdOnly_srv" :depends-on ("_package_CmdOnly_srv"))
    (:file "_package_CmdOnly_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_ContinueMotion_srv" :depends-on ("_package_NMotionCtrl_ContinueMotion_srv"))
    (:file "_package_NMotionCtrl_ContinueMotion_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_ReadDevInfo_srv" :depends-on ("_package_NMotionCtrl_ReadDevInfo_srv"))
    (:file "_package_NMotionCtrl_ReadDevInfo_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_JumpToNextCmd_srv" :depends-on ("_package_NMotionCtrl_JumpToNextCmd_srv"))
    (:file "_package_NMotionCtrl_JumpToNextCmd_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_JoyCmdMotion_srv" :depends-on ("_package_NMotionCtrl_JoyCmdMotion_srv"))
    (:file "_package_NMotionCtrl_JoyCmdMotion_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_StopMotion_srv" :depends-on ("_package_NMotionCtrl_StopMotion_srv"))
    (:file "_package_NMotionCtrl_StopMotion_srv" :depends-on ("_package"))
    (:file "OFPS1_ReadPosition_srv" :depends-on ("_package_OFPS1_ReadPosition_srv"))
    (:file "_package_OFPS1_ReadPosition_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_SuspendMotion_srv" :depends-on ("_package_NMotionCtrl_SuspendMotion_srv"))
    (:file "_package_NMotionCtrl_SuspendMotion_srv" :depends-on ("_package"))
    (:file "OFPS1_ReadDevInfo_srv" :depends-on ("_package_OFPS1_ReadDevInfo_srv"))
    (:file "_package_OFPS1_ReadDevInfo_srv" :depends-on ("_package"))
    (:file "NMotionCtrl_SetInstantVelocity_srv" :depends-on ("_package_NMotionCtrl_SetInstantVelocity_srv"))
    (:file "_package_NMotionCtrl_SetInstantVelocity_srv" :depends-on ("_package"))
  ))