/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/CDHF_Robot/srv/EMotion_RdDevType_srv.srv */
#ifndef CDHF_ROBOT_SERVICE_EMOTION_RDDEVTYPE_SRV_H
#define CDHF_ROBOT_SERVICE_EMOTION_RDDEVTYPE_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace CDHF_Robot
{
template <class ContainerAllocator>
struct EMotion_RdDevType_srvRequest_ {
  typedef EMotion_RdDevType_srvRequest_<ContainerAllocator> Type;

  EMotion_RdDevType_srvRequest_()
  {
  }

  EMotion_RdDevType_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct EMotion_RdDevType_srvRequest
typedef  ::CDHF_Robot::EMotion_RdDevType_srvRequest_<std::allocator<void> > EMotion_RdDevType_srvRequest;

typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvRequest> EMotion_RdDevType_srvRequestPtr;
typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvRequest const> EMotion_RdDevType_srvRequestConstPtr;



template <class ContainerAllocator>
struct EMotion_RdDevType_srvResponse_ {
  typedef EMotion_RdDevType_srvResponse_<ContainerAllocator> Type;

  EMotion_RdDevType_srvResponse_()
  : u8DevAddr(0)
  , u8DevType(0)
  {
  }

  EMotion_RdDevType_srvResponse_(const ContainerAllocator& _alloc)
  : u8DevAddr(0)
  , u8DevType(0)
  {
  }

  typedef uint8_t _u8DevAddr_type;
  uint8_t u8DevAddr;

  typedef uint8_t _u8DevType_type;
  uint8_t u8DevType;


  typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct EMotion_RdDevType_srvResponse
typedef  ::CDHF_Robot::EMotion_RdDevType_srvResponse_<std::allocator<void> > EMotion_RdDevType_srvResponse;

typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvResponse> EMotion_RdDevType_srvResponsePtr;
typedef boost::shared_ptr< ::CDHF_Robot::EMotion_RdDevType_srvResponse const> EMotion_RdDevType_srvResponseConstPtr;


struct EMotion_RdDevType_srv
{

typedef EMotion_RdDevType_srvRequest Request;
typedef EMotion_RdDevType_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct EMotion_RdDevType_srv
} // namespace CDHF_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/EMotion_RdDevType_srvRequest";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a56c2ab9c7c9a056a5b3f503f5a4eff";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a56c2ab9c7c9a05ULL;
  static const uint64_t static_value2 = 0x6a5b3f503f5a4effULL;
};

template<class ContainerAllocator>
struct DataType< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/EMotion_RdDevType_srvResponse";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 u8DevAddr\n\
uint8 u8DevType\n\
\n\
\n\
";
  }

  static const char* value(const  ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EMotion_RdDevType_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.u8DevAddr);
    stream.next(m.u8DevType);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EMotion_RdDevType_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<CDHF_Robot::EMotion_RdDevType_srv> {
  static const char* value() 
  {
    return "1a56c2ab9c7c9a056a5b3f503f5a4eff";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srv&) { return value(); } 
};

template<>
struct DataType<CDHF_Robot::EMotion_RdDevType_srv> {
  static const char* value() 
  {
    return "CDHF_Robot/EMotion_RdDevType_srv";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a56c2ab9c7c9a056a5b3f503f5a4eff";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/EMotion_RdDevType_srv";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a56c2ab9c7c9a056a5b3f503f5a4eff";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/EMotion_RdDevType_srv";
  }

  static const char* value(const CDHF_Robot::EMotion_RdDevType_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CDHF_ROBOT_SERVICE_EMOTION_RDDEVTYPE_SRV_H

