/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/CDHF_Robot/srv/NMotionCtrl_JumpToNextCmd_srv.srv */
#ifndef CDHF_ROBOT_SERVICE_NMOTIONCTRL_JUMPTONEXTCMD_SRV_H
#define CDHF_ROBOT_SERVICE_NMOTIONCTRL_JUMPTONEXTCMD_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace CDHF_Robot
{
template <class ContainerAllocator>
struct NMotionCtrl_JumpToNextCmd_srvRequest_ {
  typedef NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_JumpToNextCmd_srvRequest_()
  {
  }

  NMotionCtrl_JumpToNextCmd_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_JumpToNextCmd_srvRequest
typedef  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<std::allocator<void> > NMotionCtrl_JumpToNextCmd_srvRequest;

typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest> NMotionCtrl_JumpToNextCmd_srvRequestPtr;
typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest const> NMotionCtrl_JumpToNextCmd_srvRequestConstPtr;



template <class ContainerAllocator>
struct NMotionCtrl_JumpToNextCmd_srvResponse_ {
  typedef NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> Type;

  NMotionCtrl_JumpToNextCmd_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u8MotionStatus(0)
  , u8SysErrStatus(0)
  {
  }

  NMotionCtrl_JumpToNextCmd_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u8MotionStatus(0)
  , u8SysErrStatus(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint8_t _u8MotionStatus_type;
  uint8_t u8MotionStatus;

  typedef uint8_t _u8SysErrStatus_type;
  uint8_t u8SysErrStatus;


  typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_JumpToNextCmd_srvResponse
typedef  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<std::allocator<void> > NMotionCtrl_JumpToNextCmd_srvResponse;

typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse> NMotionCtrl_JumpToNextCmd_srvResponsePtr;
typedef boost::shared_ptr< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse const> NMotionCtrl_JumpToNextCmd_srvResponseConstPtr;


struct NMotionCtrl_JumpToNextCmd_srv
{

typedef NMotionCtrl_JumpToNextCmd_srvRequest Request;
typedef NMotionCtrl_JumpToNextCmd_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct NMotionCtrl_JumpToNextCmd_srv
} // namespace CDHF_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/NMotionCtrl_JumpToNextCmd_srvRequest";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "91b32a73c3781768b7ade6d95aeb80ea";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x91b32a73c3781768ULL;
  static const uint64_t static_value2 = 0xb7ade6d95aeb80eaULL;
};

template<class ContainerAllocator>
struct DataType< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/NMotionCtrl_JumpToNextCmd_srvResponse";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint8  u8MotionStatus\n\
uint8  u8SysErrStatus\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_JumpToNextCmd_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u8MotionStatus);
    stream.next(m.u8SysErrStatus);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_JumpToNextCmd_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srv> {
  static const char* value() 
  {
    return "91b32a73c3781768b7ade6d95aeb80ea";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srv&) { return value(); } 
};

template<>
struct DataType<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srv> {
  static const char* value() 
  {
    return "CDHF_Robot/NMotionCtrl_JumpToNextCmd_srv";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "91b32a73c3781768b7ade6d95aeb80ea";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/NMotionCtrl_JumpToNextCmd_srv";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "91b32a73c3781768b7ade6d95aeb80ea";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "CDHF_Robot/NMotionCtrl_JumpToNextCmd_srv";
  }

  static const char* value(const CDHF_Robot::NMotionCtrl_JumpToNextCmd_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CDHF_ROBOT_SERVICE_NMOTIONCTRL_JUMPTONEXTCMD_SRV_H

