// Generated by gencpp from file N_Robot/NMotionCtrl_JoyCmdMotion_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_JOYCMDMOTION_SRV_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_JOYCMDMOTION_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/NMotionCtrl_JoyCmdMotion_srvRequest.h>
#include <N_Robot/NMotionCtrl_JoyCmdMotion_srvResponse.h>


namespace N_Robot
{

struct NMotionCtrl_JoyCmdMotion_srv
{

typedef NMotionCtrl_JoyCmdMotion_srvRequest Request;
typedef NMotionCtrl_JoyCmdMotion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_JoyCmdMotion_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > {
  static const char* value()
  {
    return "0fae833057af8a323ca1d5d7b1f7154c";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > {
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srv";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_JOYCMDMOTION_SRV_H
