// Generated by gencpp from file N_Robot/NMotionCtrl_ReadVersion_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/NMotionCtrl_ReadVersion_srvRequest.h>
#include <N_Robot/NMotionCtrl_ReadVersion_srvResponse.h>


namespace N_Robot
{

struct NMotionCtrl_ReadVersion_srv
{

typedef NMotionCtrl_ReadVersion_srvRequest Request;
typedef NMotionCtrl_ReadVersion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_ReadVersion_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srv > {
  static const char* value()
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::NMotionCtrl_ReadVersion_srv > {
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srv";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_ReadVersion_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_ReadVersion_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_ReadVersion_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H
