// Generated by gencpp from file N_Robot/NMotionCtrl_STATPositionMode_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/NMotionCtrl_STATPositionMode_srvRequest.h>
#include <N_Robot/NMotionCtrl_STATPositionMode_srvResponse.h>


namespace N_Robot
{

struct NMotionCtrl_STATPositionMode_srv
{

typedef NMotionCtrl_STATPositionMode_srvRequest Request;
typedef NMotionCtrl_STATPositionMode_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_STATPositionMode_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srv > {
  static const char* value()
  {
    return "0a2c08f1c2df750b082bd78141196c78";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srv > {
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_STATPositionMode_srv";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_STATPositionMode_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H
