// Generated by gencpp from file N_Robot/NMotionCtrl_WaitTime_srvRequest.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRVREQUEST_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace N_Robot
{
template <class ContainerAllocator>
struct NMotionCtrl_WaitTime_srvRequest_
{
  typedef NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_WaitTime_srvRequest_()
    : u16Time(0)  {
    }
  NMotionCtrl_WaitTime_srvRequest_(const ContainerAllocator& _alloc)
    : u16Time(0)  {
  (void)_alloc;
    }



   typedef uint16_t _u16Time_type;
  _u16Time_type u16Time;




  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NMotionCtrl_WaitTime_srvRequest_

typedef ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<std::allocator<void> > NMotionCtrl_WaitTime_srvRequest;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest > NMotionCtrl_WaitTime_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest const> NMotionCtrl_WaitTime_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace N_Robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'N_Robot': ['/home/cp3/catkin_ws/src/N_Robot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf8e12609d0199caddbff9553fefaef7";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf8e12609d0199caULL;
  static const uint64_t static_value2 = 0xddbff9553fefaef7ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_WaitTime_srvRequest";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16  u16Time\n\
";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u16Time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NMotionCtrl_WaitTime_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "u16Time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.u16Time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRVREQUEST_H
