// Generated by gencpp from file N_Robot/NMotionCtrl_WaitTime_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRV_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/NMotionCtrl_WaitTime_srvRequest.h>
#include <N_Robot/NMotionCtrl_WaitTime_srvResponse.h>


namespace N_Robot
{

struct NMotionCtrl_WaitTime_srv
{

typedef NMotionCtrl_WaitTime_srvRequest Request;
typedef NMotionCtrl_WaitTime_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_WaitTime_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srv > {
  static const char* value()
  {
    return "c75e483aa662fc70477e9a09649b193a";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srv > {
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_WaitTime_srv";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_WaitTime_srvRequest> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_WaitTime_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_WaitTime_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_WaitTime_srvResponse> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_WaitTime_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_WaitTime_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_WaitTime_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_WAITTIME_SRV_H
