// Generated by gencpp from file N_Robot/NMotionCtrl_SetInstantVelocity_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRV_H
#define N_ROBOT_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/NMotionCtrl_SetInstantVelocity_srvRequest.h>
#include <N_Robot/NMotionCtrl_SetInstantVelocity_srvResponse.h>


namespace N_Robot
{

struct NMotionCtrl_SetInstantVelocity_srv
{

typedef NMotionCtrl_SetInstantVelocity_srvRequest Request;
typedef NMotionCtrl_SetInstantVelocity_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_SetInstantVelocity_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > {
  static const char* value()
  {
    return "cc788b22be1bb6ec24d9cd12ccc30f6e";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > {
  static const char* value()
  {
    return "N_Robot/NMotionCtrl_SetInstantVelocity_srv";
  }

  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > 
template<>
struct MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse> should match 
// service_traits::DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv > 
template<>
struct DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::NMotionCtrl_SetInstantVelocity_srv >::value();
  }
  static const char* value(const ::N_Robot::NMotionCtrl_SetInstantVelocity_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRV_H
