// Generated by gencpp from file N_Robot/OFPS1_ReadEncoder_srvRequest.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_OFPS1_READENCODER_SRVREQUEST_H
#define N_ROBOT_MESSAGE_OFPS1_READENCODER_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace N_Robot
{
template <class ContainerAllocator>
struct OFPS1_ReadEncoder_srvRequest_
{
  typedef OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> Type;

  OFPS1_ReadEncoder_srvRequest_()
    {
    }
  OFPS1_ReadEncoder_srvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OFPS1_ReadEncoder_srvRequest_

typedef ::N_Robot::OFPS1_ReadEncoder_srvRequest_<std::allocator<void> > OFPS1_ReadEncoder_srvRequest;

typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest > OFPS1_ReadEncoder_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest const> OFPS1_ReadEncoder_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace N_Robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'N_Robot': ['/home/cp3/catkin_ws/src/N_Robot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "N_Robot/OFPS1_ReadEncoder_srvRequest";
  }

  static const char* value(const ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OFPS1_ReadEncoder_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // N_ROBOT_MESSAGE_OFPS1_READENCODER_SRVREQUEST_H
