// Generated by gencpp from file N_Robot/OFPS1_SetPosition_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_OFPS1_SETPOSITION_SRV_H
#define N_ROBOT_MESSAGE_OFPS1_SETPOSITION_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/OFPS1_SetPosition_srvRequest.h>
#include <N_Robot/OFPS1_SetPosition_srvResponse.h>


namespace N_Robot
{

struct OFPS1_SetPosition_srv
{

typedef OFPS1_SetPosition_srvRequest Request;
typedef OFPS1_SetPosition_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OFPS1_SetPosition_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::OFPS1_SetPosition_srv > {
  static const char* value()
  {
    return "6ca74b599d4416d50467dc8670b61405";
  }

  static const char* value(const ::N_Robot::OFPS1_SetPosition_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::OFPS1_SetPosition_srv > {
  static const char* value()
  {
    return "N_Robot/OFPS1_SetPosition_srv";
  }

  static const char* value(const ::N_Robot::OFPS1_SetPosition_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::OFPS1_SetPosition_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::OFPS1_SetPosition_srv > 
template<>
struct MD5Sum< ::N_Robot::OFPS1_SetPosition_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::OFPS1_SetPosition_srv >::value();
  }
  static const char* value(const ::N_Robot::OFPS1_SetPosition_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::OFPS1_SetPosition_srvRequest> should match 
// service_traits::DataType< ::N_Robot::OFPS1_SetPosition_srv > 
template<>
struct DataType< ::N_Robot::OFPS1_SetPosition_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::OFPS1_SetPosition_srv >::value();
  }
  static const char* value(const ::N_Robot::OFPS1_SetPosition_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::OFPS1_SetPosition_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::OFPS1_SetPosition_srv > 
template<>
struct MD5Sum< ::N_Robot::OFPS1_SetPosition_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::OFPS1_SetPosition_srv >::value();
  }
  static const char* value(const ::N_Robot::OFPS1_SetPosition_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::OFPS1_SetPosition_srvResponse> should match 
// service_traits::DataType< ::N_Robot::OFPS1_SetPosition_srv > 
template<>
struct DataType< ::N_Robot::OFPS1_SetPosition_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::OFPS1_SetPosition_srv >::value();
  }
  static const char* value(const ::N_Robot::OFPS1_SetPosition_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_OFPS1_SETPOSITION_SRV_H
