// Generated by gencpp from file N_Robot/PS_ReadRawData_srv.msg
// DO NOT EDIT!


#ifndef N_ROBOT_MESSAGE_PS_READRAWDATA_SRV_H
#define N_ROBOT_MESSAGE_PS_READRAWDATA_SRV_H

#include <ros/service_traits.h>


#include <N_Robot/PS_ReadRawData_srvRequest.h>
#include <N_Robot/PS_ReadRawData_srvResponse.h>


namespace N_Robot
{

struct PS_ReadRawData_srv
{

typedef PS_ReadRawData_srvRequest Request;
typedef PS_ReadRawData_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PS_ReadRawData_srv
} // namespace N_Robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::N_Robot::PS_ReadRawData_srv > {
  static const char* value()
  {
    return "2c886ef5bb29e8b732fd683a903618fa";
  }

  static const char* value(const ::N_Robot::PS_ReadRawData_srv&) { return value(); }
};

template<>
struct DataType< ::N_Robot::PS_ReadRawData_srv > {
  static const char* value()
  {
    return "N_Robot/PS_ReadRawData_srv";
  }

  static const char* value(const ::N_Robot::PS_ReadRawData_srv&) { return value(); }
};


// service_traits::MD5Sum< ::N_Robot::PS_ReadRawData_srvRequest> should match 
// service_traits::MD5Sum< ::N_Robot::PS_ReadRawData_srv > 
template<>
struct MD5Sum< ::N_Robot::PS_ReadRawData_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::PS_ReadRawData_srv >::value();
  }
  static const char* value(const ::N_Robot::PS_ReadRawData_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::PS_ReadRawData_srvRequest> should match 
// service_traits::DataType< ::N_Robot::PS_ReadRawData_srv > 
template<>
struct DataType< ::N_Robot::PS_ReadRawData_srvRequest>
{
  static const char* value()
  {
    return DataType< ::N_Robot::PS_ReadRawData_srv >::value();
  }
  static const char* value(const ::N_Robot::PS_ReadRawData_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::N_Robot::PS_ReadRawData_srvResponse> should match 
// service_traits::MD5Sum< ::N_Robot::PS_ReadRawData_srv > 
template<>
struct MD5Sum< ::N_Robot::PS_ReadRawData_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::N_Robot::PS_ReadRawData_srv >::value();
  }
  static const char* value(const ::N_Robot::PS_ReadRawData_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::N_Robot::PS_ReadRawData_srvResponse> should match 
// service_traits::DataType< ::N_Robot::PS_ReadRawData_srv > 
template<>
struct DataType< ::N_Robot::PS_ReadRawData_srvResponse>
{
  static const char* value()
  {
    return DataType< ::N_Robot::PS_ReadRawData_srv >::value();
  }
  static const char* value(const ::N_Robot::PS_ReadRawData_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_MESSAGE_PS_READRAWDATA_SRV_H
