/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/NMotionCtrl_JoyCmdMotion_srv.srv */
#ifndef N_ROBOT_SERVICE_NMOTIONCTRL_JOYCMDMOTION_SRV_H
#define N_ROBOT_SERVICE_NMOTIONCTRL_JOYCMDMOTION_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct NMotionCtrl_JoyCmdMotion_srvRequest_ {
  typedef NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_JoyCmdMotion_srvRequest_()
  : s16JoyX(0)
  , s16JoyY(0)
  , s16JoyZ(0)
  {
  }

  NMotionCtrl_JoyCmdMotion_srvRequest_(const ContainerAllocator& _alloc)
  : s16JoyX(0)
  , s16JoyY(0)
  , s16JoyZ(0)
  {
  }

  typedef int16_t _s16JoyX_type;
  int16_t s16JoyX;

  typedef int16_t _s16JoyY_type;
  int16_t s16JoyY;

  typedef int16_t _s16JoyZ_type;
  int16_t s16JoyZ;


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_JoyCmdMotion_srvRequest
typedef  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<std::allocator<void> > NMotionCtrl_JoyCmdMotion_srvRequest;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest> NMotionCtrl_JoyCmdMotion_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest const> NMotionCtrl_JoyCmdMotion_srvRequestConstPtr;



template <class ContainerAllocator>
struct NMotionCtrl_JoyCmdMotion_srvResponse_ {
  typedef NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> Type;

  NMotionCtrl_JoyCmdMotion_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u8SysErrStatus(0)
  {
  }

  NMotionCtrl_JoyCmdMotion_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u8SysErrStatus(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint8_t _u8SysErrStatus_type;
  uint8_t u8SysErrStatus;


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_JoyCmdMotion_srvResponse
typedef  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<std::allocator<void> > NMotionCtrl_JoyCmdMotion_srvResponse;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse> NMotionCtrl_JoyCmdMotion_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse const> NMotionCtrl_JoyCmdMotion_srvResponseConstPtr;


struct NMotionCtrl_JoyCmdMotion_srv
{

typedef NMotionCtrl_JoyCmdMotion_srvRequest Request;
typedef NMotionCtrl_JoyCmdMotion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct NMotionCtrl_JoyCmdMotion_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e3751ae072886d03d16c2b3c35bb0861";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe3751ae072886d03ULL;
  static const uint64_t static_value2 = 0xd16c2b3c35bb0861ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srvRequest";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16  s16JoyX\n\
int16  s16JoyY\n\
int16  s16JoyZ\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aa73ec8fc53a03fe5edb2bc5267bea65";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaa73ec8fc53a03feULL;
  static const uint64_t static_value2 = 0x5edb2bc5267bea65ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srvResponse";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint8  u8SysErrStatus\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s16JoyX);
    stream.next(m.s16JoyY);
    stream.next(m.s16JoyZ);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_JoyCmdMotion_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u8SysErrStatus);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_JoyCmdMotion_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::NMotionCtrl_JoyCmdMotion_srv> {
  static const char* value() 
  {
    return "0fae833057af8a323ca1d5d7b1f7154c";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::NMotionCtrl_JoyCmdMotion_srv> {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0fae833057af8a323ca1d5d7b1f7154c";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0fae833057af8a323ca1d5d7b1f7154c";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_JoyCmdMotion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_JoyCmdMotion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_NMOTIONCTRL_JOYCMDMOTION_SRV_H

