/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/OFPS1_ReadDevInfo_srv.srv */
#ifndef N_ROBOT_SERVICE_OFPS1_READDEVINFO_SRV_H
#define N_ROBOT_SERVICE_OFPS1_READDEVINFO_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct OFPS1_ReadDevInfo_srvRequest_ {
  typedef OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> Type;

  OFPS1_ReadDevInfo_srvRequest_()
  {
  }

  OFPS1_ReadDevInfo_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct OFPS1_ReadDevInfo_srvRequest
typedef  ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<std::allocator<void> > OFPS1_ReadDevInfo_srvRequest;

typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvRequest> OFPS1_ReadDevInfo_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvRequest const> OFPS1_ReadDevInfo_srvRequestConstPtr;



template <class ContainerAllocator>
struct OFPS1_ReadDevInfo_srvResponse_ {
  typedef OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> Type;

  OFPS1_ReadDevInfo_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u8DevAddr(0)
  , u8DevType(0)
  , u32DevSN(0)
  {
  }

  OFPS1_ReadDevInfo_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u8DevAddr(0)
  , u8DevType(0)
  , u32DevSN(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint8_t _u8DevAddr_type;
  uint8_t u8DevAddr;

  typedef uint8_t _u8DevType_type;
  uint8_t u8DevType;

  typedef uint32_t _u32DevSN_type;
  uint32_t u32DevSN;


  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct OFPS1_ReadDevInfo_srvResponse
typedef  ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<std::allocator<void> > OFPS1_ReadDevInfo_srvResponse;

typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvResponse> OFPS1_ReadDevInfo_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadDevInfo_srvResponse const> OFPS1_ReadDevInfo_srvResponseConstPtr;


struct OFPS1_ReadDevInfo_srv
{

typedef OFPS1_ReadDevInfo_srvRequest Request;
typedef OFPS1_ReadDevInfo_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct OFPS1_ReadDevInfo_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadDevInfo_srvRequest";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4ac4faa8af4fa35586775683b4a29d63";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4ac4faa8af4fa355ULL;
  static const uint64_t static_value2 = 0x86775683b4a29d63ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadDevInfo_srvResponse";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint8  u8DevAddr\n\
uint8  u8DevType\n\
uint32 u32DevSN\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OFPS1_ReadDevInfo_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u8DevAddr);
    stream.next(m.u8DevType);
    stream.next(m.u32DevSN);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OFPS1_ReadDevInfo_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::OFPS1_ReadDevInfo_srv> {
  static const char* value() 
  {
    return "4ac4faa8af4fa35586775683b4a29d63";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::OFPS1_ReadDevInfo_srv> {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadDevInfo_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4ac4faa8af4fa35586775683b4a29d63";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadDevInfo_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4ac4faa8af4fa35586775683b4a29d63";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadDevInfo_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadDevInfo_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_OFPS1_READDEVINFO_SRV_H

