/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/PS_ReadTransData_srv.srv */
#ifndef N_ROBOT_SERVICE_PS_READTRANSDATA_SRV_H
#define N_ROBOT_SERVICE_PS_READTRANSDATA_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct PS_ReadTransData_srvRequest_ {
  typedef PS_ReadTransData_srvRequest_<ContainerAllocator> Type;

  PS_ReadTransData_srvRequest_()
  {
  }

  PS_ReadTransData_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct PS_ReadTransData_srvRequest
typedef  ::N_Robot::PS_ReadTransData_srvRequest_<std::allocator<void> > PS_ReadTransData_srvRequest;

typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvRequest> PS_ReadTransData_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvRequest const> PS_ReadTransData_srvRequestConstPtr;



template <class ContainerAllocator>
struct PS_ReadTransData_srvResponse_ {
  typedef PS_ReadTransData_srvResponse_<ContainerAllocator> Type;

  PS_ReadTransData_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u16BattVolt(0)
  , s16BattCurr(0)
  , s16BattChargeCurr(0)
  , u8Temperture(0)
  {
  }

  PS_ReadTransData_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u16BattVolt(0)
  , s16BattCurr(0)
  , s16BattChargeCurr(0)
  , u8Temperture(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint16_t _u16BattVolt_type;
  uint16_t u16BattVolt;

  typedef int16_t _s16BattCurr_type;
  int16_t s16BattCurr;

  typedef int16_t _s16BattChargeCurr_type;
  int16_t s16BattChargeCurr;

  typedef uint8_t _u8Temperture_type;
  uint8_t u8Temperture;


  typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct PS_ReadTransData_srvResponse
typedef  ::N_Robot::PS_ReadTransData_srvResponse_<std::allocator<void> > PS_ReadTransData_srvResponse;

typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvResponse> PS_ReadTransData_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::PS_ReadTransData_srvResponse const> PS_ReadTransData_srvResponseConstPtr;


struct PS_ReadTransData_srv
{

typedef PS_ReadTransData_srvRequest Request;
typedef PS_ReadTransData_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct PS_ReadTransData_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadTransData_srvRequest";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "abaef58b7907806e78b13d105be847a3";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xabaef58b7907806eULL;
  static const uint64_t static_value2 = 0x78b13d105be847a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadTransData_srvResponse";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint16 u16BattVolt\n\
int16  s16BattCurr\n\
int16  s16BattChargeCurr\n\
uint8  u8Temperture\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PS_ReadTransData_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u16BattVolt);
    stream.next(m.s16BattCurr);
    stream.next(m.s16BattChargeCurr);
    stream.next(m.u8Temperture);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PS_ReadTransData_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::PS_ReadTransData_srv> {
  static const char* value() 
  {
    return "abaef58b7907806e78b13d105be847a3";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::PS_ReadTransData_srv> {
  static const char* value() 
  {
    return "N_Robot/PS_ReadTransData_srv";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "abaef58b7907806e78b13d105be847a3";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadTransData_srv";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "abaef58b7907806e78b13d105be847a3";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadTransData_srv";
  }

  static const char* value(const N_Robot::PS_ReadTransData_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_PS_READTRANSDATA_SRV_H

