/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/PS_ReadStatus_srv.srv */
#ifndef N_ROBOT_SERVICE_PS_READSTATUS_SRV_H
#define N_ROBOT_SERVICE_PS_READSTATUS_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct PS_ReadStatus_srvRequest_ {
  typedef PS_ReadStatus_srvRequest_<ContainerAllocator> Type;

  PS_ReadStatus_srvRequest_()
  {
  }

  PS_ReadStatus_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct PS_ReadStatus_srvRequest
typedef  ::N_Robot::PS_ReadStatus_srvRequest_<std::allocator<void> > PS_ReadStatus_srvRequest;

typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvRequest> PS_ReadStatus_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvRequest const> PS_ReadStatus_srvRequestConstPtr;



template <class ContainerAllocator>
struct PS_ReadStatus_srvResponse_ {
  typedef PS_ReadStatus_srvResponse_<ContainerAllocator> Type;

  PS_ReadStatus_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u8BattOpen(0)
  , u8SwitchDown(0)
  , u8ChargerIn(0)
  , u8ChargeComp(0)
  , u8ChargeOverFlow(0)
  , u8ChargerOverVolt(0)
  , u8ChargerVoltLow(0)
  , u8ChargerOverFlow(0)
  {
  }

  PS_ReadStatus_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u8BattOpen(0)
  , u8SwitchDown(0)
  , u8ChargerIn(0)
  , u8ChargeComp(0)
  , u8ChargeOverFlow(0)
  , u8ChargerOverVolt(0)
  , u8ChargerVoltLow(0)
  , u8ChargerOverFlow(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint8_t _u8BattOpen_type;
  uint8_t u8BattOpen;

  typedef uint8_t _u8SwitchDown_type;
  uint8_t u8SwitchDown;

  typedef uint8_t _u8ChargerIn_type;
  uint8_t u8ChargerIn;

  typedef uint8_t _u8ChargeComp_type;
  uint8_t u8ChargeComp;

  typedef uint8_t _u8ChargeOverFlow_type;
  uint8_t u8ChargeOverFlow;

  typedef uint8_t _u8ChargerOverVolt_type;
  uint8_t u8ChargerOverVolt;

  typedef uint8_t _u8ChargerVoltLow_type;
  uint8_t u8ChargerVoltLow;

  typedef uint8_t _u8ChargerOverFlow_type;
  uint8_t u8ChargerOverFlow;


  typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct PS_ReadStatus_srvResponse
typedef  ::N_Robot::PS_ReadStatus_srvResponse_<std::allocator<void> > PS_ReadStatus_srvResponse;

typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvResponse> PS_ReadStatus_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::PS_ReadStatus_srvResponse const> PS_ReadStatus_srvResponseConstPtr;


struct PS_ReadStatus_srv
{

typedef PS_ReadStatus_srvRequest Request;
typedef PS_ReadStatus_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct PS_ReadStatus_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadStatus_srvRequest";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "733c182a56016889a83d22c5e6a7517f";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x733c182a56016889ULL;
  static const uint64_t static_value2 = 0xa83d22c5e6a7517fULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadStatus_srvResponse";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint8  u8BattOpen\n\
uint8  u8SwitchDown\n\
uint8  u8ChargerIn\n\
uint8  u8ChargeComp\n\
uint8  u8ChargeOverFlow\n\
uint8  u8ChargerOverVolt\n\
uint8  u8ChargerVoltLow\n\
uint8  u8ChargerOverFlow\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PS_ReadStatus_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u8BattOpen);
    stream.next(m.u8SwitchDown);
    stream.next(m.u8ChargerIn);
    stream.next(m.u8ChargeComp);
    stream.next(m.u8ChargeOverFlow);
    stream.next(m.u8ChargerOverVolt);
    stream.next(m.u8ChargerVoltLow);
    stream.next(m.u8ChargerOverFlow);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PS_ReadStatus_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::PS_ReadStatus_srv> {
  static const char* value() 
  {
    return "733c182a56016889a83d22c5e6a7517f";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::PS_ReadStatus_srv> {
  static const char* value() 
  {
    return "N_Robot/PS_ReadStatus_srv";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "733c182a56016889a83d22c5e6a7517f";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadStatus_srv";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "733c182a56016889a83d22c5e6a7517f";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/PS_ReadStatus_srv";
  }

  static const char* value(const N_Robot::PS_ReadStatus_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_PS_READSTATUS_SRV_H

