/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/NMotionCtrl_ReadVersion_srv.srv */
#ifndef N_ROBOT_SERVICE_NMOTIONCTRL_READVERSION_SRV_H
#define N_ROBOT_SERVICE_NMOTIONCTRL_READVERSION_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct NMotionCtrl_ReadVersion_srvRequest_ {
  typedef NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_ReadVersion_srvRequest_()
  {
  }

  NMotionCtrl_ReadVersion_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_ReadVersion_srvRequest
typedef  ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<std::allocator<void> > NMotionCtrl_ReadVersion_srvRequest;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest> NMotionCtrl_ReadVersion_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest const> NMotionCtrl_ReadVersion_srvRequestConstPtr;



template <class ContainerAllocator>
struct NMotionCtrl_ReadVersion_srvResponse_ {
  typedef NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> Type;

  NMotionCtrl_ReadVersion_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u16HrdVer(0)
  , f32SwVer(0.0)
  {
  }

  NMotionCtrl_ReadVersion_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u16HrdVer(0)
  , f32SwVer(0.0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint16_t _u16HrdVer_type;
  uint16_t u16HrdVer;

  typedef float _f32SwVer_type;
  float f32SwVer;


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_ReadVersion_srvResponse
typedef  ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<std::allocator<void> > NMotionCtrl_ReadVersion_srvResponse;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse> NMotionCtrl_ReadVersion_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse const> NMotionCtrl_ReadVersion_srvResponseConstPtr;


struct NMotionCtrl_ReadVersion_srv
{

typedef NMotionCtrl_ReadVersion_srvRequest Request;
typedef NMotionCtrl_ReadVersion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct NMotionCtrl_ReadVersion_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srvRequest";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x42981541a16336aaULL;
  static const uint64_t static_value2 = 0x0e736c7cf0ed27cbULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srvResponse";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint16  u16HrdVer\n\
float32 f32SwVer\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_ReadVersion_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u16HrdVer);
    stream.next(m.f32SwVer);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_ReadVersion_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::NMotionCtrl_ReadVersion_srv> {
  static const char* value() 
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::NMotionCtrl_ReadVersion_srv> {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_ReadVersion_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_ReadVersion_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_NMOTIONCTRL_READVERSION_SRV_H

