/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/NMotionCtrl_WaitTime_srv.srv */
#ifndef N_ROBOT_SERVICE_NMOTIONCTRL_WAITTIME_SRV_H
#define N_ROBOT_SERVICE_NMOTIONCTRL_WAITTIME_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct NMotionCtrl_WaitTime_srvRequest_ {
  typedef NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_WaitTime_srvRequest_()
  : u16Time(0)
  {
  }

  NMotionCtrl_WaitTime_srvRequest_(const ContainerAllocator& _alloc)
  : u16Time(0)
  {
  }

  typedef uint16_t _u16Time_type;
  uint16_t u16Time;


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_WaitTime_srvRequest
typedef  ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<std::allocator<void> > NMotionCtrl_WaitTime_srvRequest;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest> NMotionCtrl_WaitTime_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvRequest const> NMotionCtrl_WaitTime_srvRequestConstPtr;



template <class ContainerAllocator>
struct NMotionCtrl_WaitTime_srvResponse_ {
  typedef NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> Type;

  NMotionCtrl_WaitTime_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , u8SysErrStatus(0)
  {
  }

  NMotionCtrl_WaitTime_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , u8SysErrStatus(0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef uint8_t _u8SysErrStatus_type;
  uint8_t u8SysErrStatus;


  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct NMotionCtrl_WaitTime_srvResponse
typedef  ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<std::allocator<void> > NMotionCtrl_WaitTime_srvResponse;

typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvResponse> NMotionCtrl_WaitTime_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::NMotionCtrl_WaitTime_srvResponse const> NMotionCtrl_WaitTime_srvResponseConstPtr;


struct NMotionCtrl_WaitTime_srv
{

typedef NMotionCtrl_WaitTime_srvRequest Request;
typedef NMotionCtrl_WaitTime_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct NMotionCtrl_WaitTime_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bf8e12609d0199caddbff9553fefaef7";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbf8e12609d0199caULL;
  static const uint64_t static_value2 = 0xddbff9553fefaef7ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_WaitTime_srvRequest";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16  u16Time\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aa73ec8fc53a03fe5edb2bc5267bea65";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaa73ec8fc53a03feULL;
  static const uint64_t static_value2 = 0x5edb2bc5267bea65ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_WaitTime_srvResponse";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint8  u8SysErrStatus\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.u16Time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_WaitTime_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.u8SysErrStatus);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NMotionCtrl_WaitTime_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::NMotionCtrl_WaitTime_srv> {
  static const char* value() 
  {
    return "c75e483aa662fc70477e9a09649b193a";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::NMotionCtrl_WaitTime_srv> {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_WaitTime_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c75e483aa662fc70477e9a09649b193a";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_WaitTime_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c75e483aa662fc70477e9a09649b193a";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/NMotionCtrl_WaitTime_srv";
  }

  static const char* value(const N_Robot::NMotionCtrl_WaitTime_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_NMOTIONCTRL_WAITTIME_SRV_H

