/* Auto-generated by genmsg_cpp for file /home/ubuntu/dev/ros/N_Robot/srv/OFPS1_ReadEncoder_srv.srv */
#ifndef N_ROBOT_SERVICE_OFPS1_READENCODER_SRV_H
#define N_ROBOT_SERVICE_OFPS1_READENCODER_SRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace N_Robot
{
template <class ContainerAllocator>
struct OFPS1_ReadEncoder_srvRequest_ {
  typedef OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> Type;

  OFPS1_ReadEncoder_srvRequest_()
  {
  }

  OFPS1_ReadEncoder_srvRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct OFPS1_ReadEncoder_srvRequest
typedef  ::N_Robot::OFPS1_ReadEncoder_srvRequest_<std::allocator<void> > OFPS1_ReadEncoder_srvRequest;

typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest> OFPS1_ReadEncoder_srvRequestPtr;
typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvRequest const> OFPS1_ReadEncoder_srvRequestConstPtr;



template <class ContainerAllocator>
struct OFPS1_ReadEncoder_srvResponse_ {
  typedef OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> Type;

  OFPS1_ReadEncoder_srvResponse_()
  : s32ErrCode(0)
  , strErrInfo()
  , f32Encoder1(0.0)
  , f32Encoder2(0.0)
  , f32Encoder3(0.0)
  {
  }

  OFPS1_ReadEncoder_srvResponse_(const ContainerAllocator& _alloc)
  : s32ErrCode(0)
  , strErrInfo(_alloc)
  , f32Encoder1(0.0)
  , f32Encoder2(0.0)
  , f32Encoder3(0.0)
  {
  }

  typedef int32_t _s32ErrCode_type;
  int32_t s32ErrCode;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  strErrInfo;

  typedef float _f32Encoder1_type;
  float f32Encoder1;

  typedef float _f32Encoder2_type;
  float f32Encoder2;

  typedef float _f32Encoder3_type;
  float f32Encoder3;


  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct OFPS1_ReadEncoder_srvResponse
typedef  ::N_Robot::OFPS1_ReadEncoder_srvResponse_<std::allocator<void> > OFPS1_ReadEncoder_srvResponse;

typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvResponse> OFPS1_ReadEncoder_srvResponsePtr;
typedef boost::shared_ptr< ::N_Robot::OFPS1_ReadEncoder_srvResponse const> OFPS1_ReadEncoder_srvResponseConstPtr;


struct OFPS1_ReadEncoder_srv
{

typedef OFPS1_ReadEncoder_srvRequest Request;
typedef OFPS1_ReadEncoder_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct OFPS1_ReadEncoder_srv
} // namespace N_Robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadEncoder_srvRequest";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fde9ee8a9f7ccc3f22d8f39b640b16d0";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfde9ee8a9f7ccc3fULL;
  static const uint64_t static_value2 = 0x22d8f39b640b16d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadEncoder_srvResponse";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
float32  f32Encoder1\n\
float32  f32Encoder2\n\
float32  f32Encoder3\n\
\n\
\n\
";
  }

  static const char* value(const  ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OFPS1_ReadEncoder_srvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.s32ErrCode);
    stream.next(m.strErrInfo);
    stream.next(m.f32Encoder1);
    stream.next(m.f32Encoder2);
    stream.next(m.f32Encoder3);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OFPS1_ReadEncoder_srvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<N_Robot::OFPS1_ReadEncoder_srv> {
  static const char* value() 
  {
    return "fde9ee8a9f7ccc3f22d8f39b640b16d0";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srv&) { return value(); } 
};

template<>
struct DataType<N_Robot::OFPS1_ReadEncoder_srv> {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadEncoder_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fde9ee8a9f7ccc3f22d8f39b640b16d0";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadEncoder_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fde9ee8a9f7ccc3f22d8f39b640b16d0";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "N_Robot/OFPS1_ReadEncoder_srv";
  }

  static const char* value(const N_Robot::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // N_ROBOT_SERVICE_OFPS1_READENCODER_SRV_H

