// Generated by gencpp from file navigator_q2/CmdOnly_srv.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_CMDONLY_SRV_H
#define NAVIGATOR_Q2_MESSAGE_CMDONLY_SRV_H

#include <ros/service_traits.h>


#include <navigator_q2/CmdOnly_srvRequest.h>
#include <navigator_q2/CmdOnly_srvResponse.h>


namespace navigator_q2
{

struct CmdOnly_srv
{

typedef CmdOnly_srvRequest Request;
typedef CmdOnly_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CmdOnly_srv
} // namespace navigator_q2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigator_q2::CmdOnly_srv > {
  static const char* value()
  {
    return "2cbb63f69963641e39b44412655d5578";
  }

  static const char* value(const ::navigator_q2::CmdOnly_srv&) { return value(); }
};

template<>
struct DataType< ::navigator_q2::CmdOnly_srv > {
  static const char* value()
  {
    return "navigator_q2/CmdOnly_srv";
  }

  static const char* value(const ::navigator_q2::CmdOnly_srv&) { return value(); }
};


// service_traits::MD5Sum< ::navigator_q2::CmdOnly_srvRequest> should match 
// service_traits::MD5Sum< ::navigator_q2::CmdOnly_srv > 
template<>
struct MD5Sum< ::navigator_q2::CmdOnly_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::CmdOnly_srv >::value();
  }
  static const char* value(const ::navigator_q2::CmdOnly_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::CmdOnly_srvRequest> should match 
// service_traits::DataType< ::navigator_q2::CmdOnly_srv > 
template<>
struct DataType< ::navigator_q2::CmdOnly_srvRequest>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::CmdOnly_srv >::value();
  }
  static const char* value(const ::navigator_q2::CmdOnly_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigator_q2::CmdOnly_srvResponse> should match 
// service_traits::MD5Sum< ::navigator_q2::CmdOnly_srv > 
template<>
struct MD5Sum< ::navigator_q2::CmdOnly_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::CmdOnly_srv >::value();
  }
  static const char* value(const ::navigator_q2::CmdOnly_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::CmdOnly_srvResponse> should match 
// service_traits::DataType< ::navigator_q2::CmdOnly_srv > 
template<>
struct DataType< ::navigator_q2::CmdOnly_srvResponse>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::CmdOnly_srv >::value();
  }
  static const char* value(const ::navigator_q2::CmdOnly_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_CMDONLY_SRV_H
