// Generated by gencpp from file navigator_q2/CyberJoy_msg.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_CYBERJOY_MSG_H
#define NAVIGATOR_Q2_MESSAGE_CYBERJOY_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigator_q2
{
template <class ContainerAllocator>
struct CyberJoy_msg_
{
  typedef CyberJoy_msg_<ContainerAllocator> Type;

  CyberJoy_msg_()
    : bValid(false)
    , i16VelY(0)
    , i16VelX(0)
    , i16VelR(0)
    , i16VelR2(0)  {
    }
  CyberJoy_msg_(const ContainerAllocator& _alloc)
    : bValid(false)
    , i16VelY(0)
    , i16VelX(0)
    , i16VelR(0)
    , i16VelR2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _bValid_type;
  _bValid_type bValid;

   typedef int16_t _i16VelY_type;
  _i16VelY_type i16VelY;

   typedef int16_t _i16VelX_type;
  _i16VelX_type i16VelX;

   typedef int16_t _i16VelR_type;
  _i16VelR_type i16VelR;

   typedef int16_t _i16VelR2_type;
  _i16VelR2_type i16VelR2;




  typedef boost::shared_ptr< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> const> ConstPtr;

}; // struct CyberJoy_msg_

typedef ::navigator_q2::CyberJoy_msg_<std::allocator<void> > CyberJoy_msg;

typedef boost::shared_ptr< ::navigator_q2::CyberJoy_msg > CyberJoy_msgPtr;
typedef boost::shared_ptr< ::navigator_q2::CyberJoy_msg const> CyberJoy_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigator_q2::CyberJoy_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigator_q2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'navigator_q2': ['/home/cp3/catkin_ws/src/navigator_q2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0201e833065447e9b7599cb5c15e657";
  }

  static const char* value(const ::navigator_q2::CyberJoy_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0201e833065447eULL;
  static const uint64_t static_value2 = 0x9b7599cb5c15e657ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigator_q2/CyberJoy_msg";
  }

  static const char* value(const ::navigator_q2::CyberJoy_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Cyber Joy valid info\n\
bool bValid\n\
#Velocity info\n\
int16 i16VelY\n\
int16 i16VelX\n\
int16 i16VelR\n\
int16 i16VelR2\n\
\n\
";
  }

  static const char* value(const ::navigator_q2::CyberJoy_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bValid);
      stream.next(m.i16VelY);
      stream.next(m.i16VelX);
      stream.next(m.i16VelR);
      stream.next(m.i16VelR2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CyberJoy_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigator_q2::CyberJoy_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigator_q2::CyberJoy_msg_<ContainerAllocator>& v)
  {
    s << indent << "bValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bValid);
    s << indent << "i16VelY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.i16VelY);
    s << indent << "i16VelX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.i16VelX);
    s << indent << "i16VelR: ";
    Printer<int16_t>::stream(s, indent + "  ", v.i16VelR);
    s << indent << "i16VelR2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.i16VelR2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_CYBERJOY_MSG_H
