// Generated by gencpp from file navigator_q2/NMotionCtrl_SetInstantVelocity_srvRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRVREQUEST_H
#define NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigator_q2
{
template <class ContainerAllocator>
struct NMotionCtrl_SetInstantVelocity_srvRequest_
{
  typedef NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> Type;

  NMotionCtrl_SetInstantVelocity_srvRequest_()
    : s16DirectionAngle(0)
    , u16LinearVelocity(0)
    , s16AngularVelocity(0)  {
    }
  NMotionCtrl_SetInstantVelocity_srvRequest_(const ContainerAllocator& _alloc)
    : s16DirectionAngle(0)
    , u16LinearVelocity(0)
    , s16AngularVelocity(0)  {
  (void)_alloc;
    }



   typedef int16_t _s16DirectionAngle_type;
  _s16DirectionAngle_type s16DirectionAngle;

   typedef uint16_t _u16LinearVelocity_type;
  _u16LinearVelocity_type u16LinearVelocity;

   typedef int16_t _s16AngularVelocity_type;
  _s16AngularVelocity_type s16AngularVelocity;




  typedef boost::shared_ptr< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NMotionCtrl_SetInstantVelocity_srvRequest_

typedef ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<std::allocator<void> > NMotionCtrl_SetInstantVelocity_srvRequest;

typedef boost::shared_ptr< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest > NMotionCtrl_SetInstantVelocity_srvRequestPtr;
typedef boost::shared_ptr< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest const> NMotionCtrl_SetInstantVelocity_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigator_q2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'navigator_q2': ['/home/cp3/catkin_ws/src/navigator_q2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c02ce47bbb12a1161467670feda08fa";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c02ce47bbb12a11ULL;
  static const uint64_t static_value2 = 0x61467670feda08faULL;
};

template<class ContainerAllocator>
struct DataType< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigator_q2/NMotionCtrl_SetInstantVelocity_srvRequest";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16  s16DirectionAngle\n\
uint16 u16LinearVelocity\n\
int16  s16AngularVelocity\n\
";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s16DirectionAngle);
      stream.next(m.u16LinearVelocity);
      stream.next(m.s16AngularVelocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NMotionCtrl_SetInstantVelocity_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigator_q2::NMotionCtrl_SetInstantVelocity_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "s16DirectionAngle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16DirectionAngle);
    s << indent << "u16LinearVelocity: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.u16LinearVelocity);
    s << indent << "s16AngularVelocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16AngularVelocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETINSTANTVELOCITY_SRVREQUEST_H
