// Generated by gencpp from file navigator_q2/NMotionCtrl_SMATSpeedMode_srv.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SMATSPEEDMODE_SRV_H
#define NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SMATSPEEDMODE_SRV_H

#include <ros/service_traits.h>


#include <navigator_q2/NMotionCtrl_SMATSpeedMode_srvRequest.h>
#include <navigator_q2/NMotionCtrl_SMATSpeedMode_srvResponse.h>


namespace navigator_q2
{

struct NMotionCtrl_SMATSpeedMode_srv
{

typedef NMotionCtrl_SMATSpeedMode_srvRequest Request;
typedef NMotionCtrl_SMATSpeedMode_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_SMATSpeedMode_srv
} // namespace navigator_q2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > {
  static const char* value()
  {
    return "cc788b22be1bb6ec24d9cd12ccc30f6e";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv&) { return value(); }
};

template<>
struct DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > {
  static const char* value()
  {
    return "navigator_q2/NMotionCtrl_SMATSpeedMode_srv";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv&) { return value(); }
};


// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_SMATSpeedMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SMATSpeedMode_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SMATSPEEDMODE_SRV_H
