// Generated by gencpp from file navigator_q2/NMotionCtrl_ReadVersion_srv.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H
#define NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H

#include <ros/service_traits.h>


#include <navigator_q2/NMotionCtrl_ReadVersion_srvRequest.h>
#include <navigator_q2/NMotionCtrl_ReadVersion_srvResponse.h>


namespace navigator_q2
{

struct NMotionCtrl_ReadVersion_srv
{

typedef NMotionCtrl_ReadVersion_srvRequest Request;
typedef NMotionCtrl_ReadVersion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_ReadVersion_srv
} // namespace navigator_q2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srv > {
  static const char* value()
  {
    return "42981541a16336aa0e736c7cf0ed27cb";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srv&) { return value(); }
};

template<>
struct DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srv > {
  static const char* value()
  {
    return "navigator_q2/NMotionCtrl_ReadVersion_srv";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srv&) { return value(); }
};


// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_ReadVersion_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_ReadVersion_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_READVERSION_SRV_H
