// Generated by gencpp from file navigator_q2/NMotionCtrl_STATPositionMode_srv.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H
#define NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H

#include <ros/service_traits.h>


#include <navigator_q2/NMotionCtrl_STATPositionMode_srvRequest.h>
#include <navigator_q2/NMotionCtrl_STATPositionMode_srvResponse.h>


namespace navigator_q2
{

struct NMotionCtrl_STATPositionMode_srv
{

typedef NMotionCtrl_STATPositionMode_srvRequest Request;
typedef NMotionCtrl_STATPositionMode_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_STATPositionMode_srv
} // namespace navigator_q2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > {
  static const char* value()
  {
    return "0a2c08f1c2df750b082bd78141196c78";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srv&) { return value(); }
};

template<>
struct DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > {
  static const char* value()
  {
    return "navigator_q2/NMotionCtrl_STATPositionMode_srv";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srv&) { return value(); }
};


// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_STATPositionMode_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_STATPositionMode_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_STATPOSITIONMODE_SRV_H
