// Generated by gencpp from file navigator_q2/NMotionCtrl_SetDir_srv.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETDIR_SRV_H
#define NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETDIR_SRV_H

#include <ros/service_traits.h>


#include <navigator_q2/NMotionCtrl_SetDir_srvRequest.h>
#include <navigator_q2/NMotionCtrl_SetDir_srvResponse.h>


namespace navigator_q2
{

struct NMotionCtrl_SetDir_srv
{

typedef NMotionCtrl_SetDir_srvRequest Request;
typedef NMotionCtrl_SetDir_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NMotionCtrl_SetDir_srv
} // namespace navigator_q2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srv > {
  static const char* value()
  {
    return "3c0466cf448f658bf8c511c00f4f5d44";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srv&) { return value(); }
};

template<>
struct DataType< ::navigator_q2::NMotionCtrl_SetDir_srv > {
  static const char* value()
  {
    return "navigator_q2/NMotionCtrl_SetDir_srv";
  }

  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srv&) { return value(); }
};


// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srvRequest> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_SetDir_srvRequest> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_SetDir_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_SetDir_srvRequest>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_SetDir_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srvResponse> should match 
// service_traits::MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srv > 
template<>
struct MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigator_q2::NMotionCtrl_SetDir_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigator_q2::NMotionCtrl_SetDir_srvResponse> should match 
// service_traits::DataType< ::navigator_q2::NMotionCtrl_SetDir_srv > 
template<>
struct DataType< ::navigator_q2::NMotionCtrl_SetDir_srvResponse>
{
  static const char* value()
  {
    return DataType< ::navigator_q2::NMotionCtrl_SetDir_srv >::value();
  }
  static const char* value(const ::navigator_q2::NMotionCtrl_SetDir_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_NMOTIONCTRL_SETDIR_SRV_H
