// Generated by gencpp from file navigator_q2/OFPS1_ReadEncoder_srvResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_OFPS1_READENCODER_SRVRESPONSE_H
#define NAVIGATOR_Q2_MESSAGE_OFPS1_READENCODER_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigator_q2
{
template <class ContainerAllocator>
struct OFPS1_ReadEncoder_srvResponse_
{
  typedef OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> Type;

  OFPS1_ReadEncoder_srvResponse_()
    : s32ErrCode(0)
    , strErrInfo()
    , f32Encoder1(0.0)
    , f32Encoder2(0.0)
    , f32Encoder3(0.0)  {
    }
  OFPS1_ReadEncoder_srvResponse_(const ContainerAllocator& _alloc)
    : s32ErrCode(0)
    , strErrInfo(_alloc)
    , f32Encoder1(0.0)
    , f32Encoder2(0.0)
    , f32Encoder3(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _s32ErrCode_type;
  _s32ErrCode_type s32ErrCode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  _strErrInfo_type strErrInfo;

   typedef float _f32Encoder1_type;
  _f32Encoder1_type f32Encoder1;

   typedef float _f32Encoder2_type;
  _f32Encoder2_type f32Encoder2;

   typedef float _f32Encoder3_type;
  _f32Encoder3_type f32Encoder3;




  typedef boost::shared_ptr< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OFPS1_ReadEncoder_srvResponse_

typedef ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<std::allocator<void> > OFPS1_ReadEncoder_srvResponse;

typedef boost::shared_ptr< ::navigator_q2::OFPS1_ReadEncoder_srvResponse > OFPS1_ReadEncoder_srvResponsePtr;
typedef boost::shared_ptr< ::navigator_q2::OFPS1_ReadEncoder_srvResponse const> OFPS1_ReadEncoder_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigator_q2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'navigator_q2': ['/home/cp3/catkin_ws/src/navigator_q2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fde9ee8a9f7ccc3f22d8f39b640b16d0";
  }

  static const char* value(const ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfde9ee8a9f7ccc3fULL;
  static const uint64_t static_value2 = 0x22d8f39b640b16d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigator_q2/OFPS1_ReadEncoder_srvResponse";
  }

  static const char* value(const ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
float32  f32Encoder1\n\
float32  f32Encoder2\n\
float32  f32Encoder3\n\
\n\
";
  }

  static const char* value(const ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s32ErrCode);
      stream.next(m.strErrInfo);
      stream.next(m.f32Encoder1);
      stream.next(m.f32Encoder2);
      stream.next(m.f32Encoder3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OFPS1_ReadEncoder_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigator_q2::OFPS1_ReadEncoder_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "s32ErrCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.s32ErrCode);
    s << indent << "strErrInfo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strErrInfo);
    s << indent << "f32Encoder1: ";
    Printer<float>::stream(s, indent + "  ", v.f32Encoder1);
    s << indent << "f32Encoder2: ";
    Printer<float>::stream(s, indent + "  ", v.f32Encoder2);
    s << indent << "f32Encoder3: ";
    Printer<float>::stream(s, indent + "  ", v.f32Encoder3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_OFPS1_READENCODER_SRVRESPONSE_H
