// Generated by gencpp from file navigator_q2/PS_ReadTransData_srvResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATOR_Q2_MESSAGE_PS_READTRANSDATA_SRVRESPONSE_H
#define NAVIGATOR_Q2_MESSAGE_PS_READTRANSDATA_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigator_q2
{
template <class ContainerAllocator>
struct PS_ReadTransData_srvResponse_
{
  typedef PS_ReadTransData_srvResponse_<ContainerAllocator> Type;

  PS_ReadTransData_srvResponse_()
    : s32ErrCode(0)
    , strErrInfo()
    , u16BattVolt(0)
    , s16BattCurr(0)
    , s16BattChargeCurr(0)
    , u8Temperture(0)  {
    }
  PS_ReadTransData_srvResponse_(const ContainerAllocator& _alloc)
    : s32ErrCode(0)
    , strErrInfo(_alloc)
    , u16BattVolt(0)
    , s16BattCurr(0)
    , s16BattChargeCurr(0)
    , u8Temperture(0)  {
  (void)_alloc;
    }



   typedef int32_t _s32ErrCode_type;
  _s32ErrCode_type s32ErrCode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strErrInfo_type;
  _strErrInfo_type strErrInfo;

   typedef uint16_t _u16BattVolt_type;
  _u16BattVolt_type u16BattVolt;

   typedef int16_t _s16BattCurr_type;
  _s16BattCurr_type s16BattCurr;

   typedef int16_t _s16BattChargeCurr_type;
  _s16BattChargeCurr_type s16BattChargeCurr;

   typedef uint8_t _u8Temperture_type;
  _u8Temperture_type u8Temperture;




  typedef boost::shared_ptr< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PS_ReadTransData_srvResponse_

typedef ::navigator_q2::PS_ReadTransData_srvResponse_<std::allocator<void> > PS_ReadTransData_srvResponse;

typedef boost::shared_ptr< ::navigator_q2::PS_ReadTransData_srvResponse > PS_ReadTransData_srvResponsePtr;
typedef boost::shared_ptr< ::navigator_q2::PS_ReadTransData_srvResponse const> PS_ReadTransData_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigator_q2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'navigator_q2': ['/home/cp3/catkin_ws/src/navigator_q2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abaef58b7907806e78b13d105be847a3";
  }

  static const char* value(const ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabaef58b7907806eULL;
  static const uint64_t static_value2 = 0x78b13d105be847a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigator_q2/PS_ReadTransData_srvResponse";
  }

  static const char* value(const ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  s32ErrCode\n\
string strErrInfo\n\
uint16 u16BattVolt\n\
int16  s16BattCurr\n\
int16  s16BattChargeCurr\n\
uint8  u8Temperture\n\
\n\
";
  }

  static const char* value(const ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s32ErrCode);
      stream.next(m.strErrInfo);
      stream.next(m.u16BattVolt);
      stream.next(m.s16BattCurr);
      stream.next(m.s16BattChargeCurr);
      stream.next(m.u8Temperture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PS_ReadTransData_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigator_q2::PS_ReadTransData_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "s32ErrCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.s32ErrCode);
    s << indent << "strErrInfo: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strErrInfo);
    s << indent << "u16BattVolt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.u16BattVolt);
    s << indent << "s16BattCurr: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16BattCurr);
    s << indent << "s16BattChargeCurr: ";
    Printer<int16_t>::stream(s, indent + "  ", v.s16BattChargeCurr);
    s << indent << "u8Temperture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.u8Temperture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATOR_Q2_MESSAGE_PS_READTRANSDATA_SRVRESPONSE_H
