(cl:in-package N_Robot-msg)
(cl:export '(BVALID-VAL
          BVALID
          I16JOY1X-VAL
          I16JOY1X
          I16JOY1Y-VAL
          I16JOY1Y
          I16JOY1Z-VAL
          I16JOY1Z
          I16JOY2X-VAL
          I16JOY2X
          I16JOY2Y-VAL
          I16JOY2Y
          I16JOY3X-VAL
          I16JOY3X
          I16JOY3Y-VAL
          I16JOY3Y
          U16POTA-VAL
          U16POTA
          U16POTB-VAL
          U16POTB
          U8BAND-VAL
          U8BAND
          I8ENCA-VAL
          I8ENCA
          I8ENCB-VAL
          I8ENCB
          U16BUTTON-VAL
          U16BUTTON
))