# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from N_Robot/CyberJoy_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CyberJoy_msg(genpy.Message):
  _md5sum = "f0201e833065447e9b7599cb5c15e657"
  _type = "N_Robot/CyberJoy_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Cyber Joy valid info
bool bValid
#Velocity info
int16 i16VelY
int16 i16VelX
int16 i16VelR
int16 i16VelR2

"""
  __slots__ = ['bValid','i16VelY','i16VelX','i16VelR','i16VelR2']
  _slot_types = ['bool','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bValid,i16VelY,i16VelX,i16VelR,i16VelR2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CyberJoy_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bValid is None:
        self.bValid = False
      if self.i16VelY is None:
        self.i16VelY = 0
      if self.i16VelX is None:
        self.i16VelX = 0
      if self.i16VelR is None:
        self.i16VelR = 0
      if self.i16VelR2 is None:
        self.i16VelR2 = 0
    else:
      self.bValid = False
      self.i16VelY = 0
      self.i16VelX = 0
      self.i16VelR = 0
      self.i16VelR2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4h.pack(_x.bValid, _x.i16VelY, _x.i16VelX, _x.i16VelR, _x.i16VelR2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.bValid, _x.i16VelY, _x.i16VelX, _x.i16VelR, _x.i16VelR2,) = _struct_B4h.unpack(str[start:end])
      self.bValid = bool(self.bValid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4h.pack(_x.bValid, _x.i16VelY, _x.i16VelX, _x.i16VelR, _x.i16VelR2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.bValid, _x.i16VelY, _x.i16VelX, _x.i16VelR, _x.i16VelR2,) = _struct_B4h.unpack(str[start:end])
      self.bValid = bool(self.bValid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4h = struct.Struct("<B4h")
