# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from N_Robot/NMotionCtrl_ReadMotionStatus_srvRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NMotionCtrl_ReadMotionStatus_srvRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "N_Robot/NMotionCtrl_ReadMotionStatus_srvRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NMotionCtrl_ReadMotionStatus_srvRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from N_Robot/NMotionCtrl_ReadMotionStatus_srvResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NMotionCtrl_ReadMotionStatus_srvResponse(genpy.Message):
  _md5sum = "cab3d3372c649fc51ca4cd10570bd6c5"
  _type = "N_Robot/NMotionCtrl_ReadMotionStatus_srvResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32  s32ErrCode
string strErrInfo
uint8  u8MotionStatus
uint8  u8SysErrStatus
uint8  u8MotorErrStatus
uint8  u8MotionBufCnt
uint8  u8CrtMotionBufAddr
uint8  u8CmdBufCnt
uint8  u8CrtCmdBufAddr

"""
  __slots__ = ['s32ErrCode','strErrInfo','u8MotionStatus','u8SysErrStatus','u8MotorErrStatus','u8MotionBufCnt','u8CrtMotionBufAddr','u8CmdBufCnt','u8CrtCmdBufAddr']
  _slot_types = ['int32','string','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       s32ErrCode,strErrInfo,u8MotionStatus,u8SysErrStatus,u8MotorErrStatus,u8MotionBufCnt,u8CrtMotionBufAddr,u8CmdBufCnt,u8CrtCmdBufAddr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NMotionCtrl_ReadMotionStatus_srvResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.s32ErrCode is None:
        self.s32ErrCode = 0
      if self.strErrInfo is None:
        self.strErrInfo = ''
      if self.u8MotionStatus is None:
        self.u8MotionStatus = 0
      if self.u8SysErrStatus is None:
        self.u8SysErrStatus = 0
      if self.u8MotorErrStatus is None:
        self.u8MotorErrStatus = 0
      if self.u8MotionBufCnt is None:
        self.u8MotionBufCnt = 0
      if self.u8CrtMotionBufAddr is None:
        self.u8CrtMotionBufAddr = 0
      if self.u8CmdBufCnt is None:
        self.u8CmdBufCnt = 0
      if self.u8CrtCmdBufAddr is None:
        self.u8CrtCmdBufAddr = 0
    else:
      self.s32ErrCode = 0
      self.strErrInfo = ''
      self.u8MotionStatus = 0
      self.u8SysErrStatus = 0
      self.u8MotorErrStatus = 0
      self.u8MotionBufCnt = 0
      self.u8CrtMotionBufAddr = 0
      self.u8CmdBufCnt = 0
      self.u8CrtCmdBufAddr = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.s32ErrCode))
      _x = self.strErrInfo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7B.pack(_x.u8MotionStatus, _x.u8SysErrStatus, _x.u8MotorErrStatus, _x.u8MotionBufCnt, _x.u8CrtMotionBufAddr, _x.u8CmdBufCnt, _x.u8CrtCmdBufAddr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.s32ErrCode,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.strErrInfo = str[start:end].decode('utf-8')
      else:
        self.strErrInfo = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.u8MotionStatus, _x.u8SysErrStatus, _x.u8MotorErrStatus, _x.u8MotionBufCnt, _x.u8CrtMotionBufAddr, _x.u8CmdBufCnt, _x.u8CrtCmdBufAddr,) = _struct_7B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.s32ErrCode))
      _x = self.strErrInfo
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7B.pack(_x.u8MotionStatus, _x.u8SysErrStatus, _x.u8MotorErrStatus, _x.u8MotionBufCnt, _x.u8CrtMotionBufAddr, _x.u8CmdBufCnt, _x.u8CrtCmdBufAddr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.s32ErrCode,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.strErrInfo = str[start:end].decode('utf-8')
      else:
        self.strErrInfo = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.u8MotionStatus, _x.u8SysErrStatus, _x.u8MotorErrStatus, _x.u8MotionBufCnt, _x.u8CrtMotionBufAddr, _x.u8CmdBufCnt, _x.u8CrtCmdBufAddr,) = _struct_7B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_7B = struct.Struct("<7B")
class NMotionCtrl_ReadMotionStatus_srv(object):
  _type          = 'N_Robot/NMotionCtrl_ReadMotionStatus_srv'
  _md5sum = 'cab3d3372c649fc51ca4cd10570bd6c5'
  _request_class  = NMotionCtrl_ReadMotionStatus_srvRequest
  _response_class = NMotionCtrl_ReadMotionStatus_srvResponse
