(cl:in-package N_Robot-srv)
(cl:export '(S32ERRCODE-VAL
          S32ERRCODE
          STRERRINFO-VAL
          STRERRINFO
          U8MOTIONSTATUS-VAL
          U8MOTIONSTATUS
          U8SYSERRSTATUS-VAL
          U8SYSERRSTATUS
          U8MOTORERRSTATUS-VAL
          U8MOTORERRSTATUS
          U8MOTIONBUFCNT-VAL
          U8MOTIONBUFCNT
          U8CRTMOTIONBUFADDR-VAL
          U8CRTMOTIONBUFADDR
          U8CMDBUFCNT-VAL
          U8CMDBUFCNT
          U8CRTCMDBUFADDR-VAL
          U8CRTCMDBUFADDR
))